export function generateApiRoute(emailName: string, emailPath: string, examplePayload: string = '{}'): string {
  return `/* eslint-disable */
// This file is generated by nuxt-generation-emails. Do not modify it manually.

import { defineEventHandler, readBody, createError } from 'h3'
import { useNitroApp } from '#imports'
import { render } from '@vue-email/render'
import EmailTemplate from '~/emails/${emailPath}.vue'

defineRouteMeta({
  openAPI: {
    tags: ['nuxt-generation-emails'],
    summary: 'Send ${emailName} email',
    description: 'Render and send the ${emailPath} email template.',
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            example: ${examplePayload},
            additionalProperties: true,
            description: '${emailName} props payload',
          },
        },
      },
    },
    responses: {
      200: {
        description: 'Email rendered successfully',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                success: { type: 'boolean' },
                message: { type: 'string' },
                html: { type: 'string' },
              },
              required: ['success', 'message', 'html'],
            },
          },
        },
      },
      500: {
        description: 'Failed to render or send email',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                statusCode: { type: 'number', example: 500 },
                statusMessage: { type: 'string' },
              },
              required: ['statusCode', 'statusMessage'],
            },
          },
        },
      },
    },
  },
})

export default defineEventHandler(async (event) => {
  const body = await readBody<Record<string, unknown>>(event)

  try {
    const html = await render(EmailTemplate, body, { pretty: true })

    const nitro = useNitroApp()
    // @ts-ignore - custom hook
    await nitro.hooks.callHook('nuxt-gen-emails:send', { html, data: body })

    return { success: true, message: 'Email rendered successfully', html }
  }
  catch (error: unknown) {
    const message = error instanceof Error ? error.message : 'Failed to render or send email'
    throw createError({ statusCode: 500, statusMessage: message })
  }
})
`
}
