export function generateApiRoute(emailName: string, emailPath: string, examplePayload: string = '{}'): string {
  return `/* eslint-disable */
// This file is generated by nuxt-generation-emails. Do not modify it manually.

import { defineEventHandler, readBody, createError } from 'h3'
import { useNitroApp, useRuntimeConfig } from '#imports'
import { readFileSync, existsSync, readdirSync } from 'node:fs'
import { join, basename } from 'node:path'
import mjml2html from 'mjml'
import Handlebars from 'handlebars'

/**
 * Register all .mjml files from the components directory as Handlebars partials.
 * This lets templates use {{> partialName}} to include reusable MJML snippets.
 */
function registerMjmlPartials(emailsDir: string): void {
  const componentsDir = join(emailsDir, 'components')
  if (!existsSync(componentsDir)) return

  {
    const files = readdirSync(componentsDir)

    for (const file of files) {
      if (!file.endsWith('.mjml')) continue
      const partialName = basename(file, '.mjml')
      const partialSource = readFileSync(join(componentsDir, file), 'utf-8')
      Handlebars.registerPartial(partialName, partialSource)
    }
  }
}

type SendData<TAdditional extends Record<string, unknown> = Record<string, unknown>> = {
  to?: string
  from?: string
  subject?: string
} & TAdditional

type NuxtGenEmailsApiBody<
  TTemplateData extends Record<string, unknown> = Record<string, unknown>,
  TSendData extends Record<string, unknown> = SendData,
> = {
  templateData: TTemplateData
  sendData: TSendData
}

defineRouteMeta({
  openAPI: {
    tags: ['nuxt-generation-emails'],
    summary: 'Send ${emailName} email',
    description: 'Render and send the ${emailPath} email template.',
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            description: '${emailName} request payload',
            properties: {
              templateData: {
                type: 'object',
                description: '${emailName} props payload',
                additionalProperties: true,
                example: ${examplePayload},
              },
              sendData: {
                type: 'object',
                description: 'Send provider metadata (to/from/subject and any additional fields)',
                additionalProperties: true,
                properties: {
                  to: { type: 'string', example: 'test@example.com' },
                  from: { type: 'string', example: 'test@example.com' },
                  subject: { type: 'string', example: 'Sending with Twilio SendGrid is Fun' },
                },
              },
            },
            required: ['templateData', 'sendData'],
          },
        },
      },
    },
    responses: {
      200: {
        description: 'Email rendered successfully',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                success: { type: 'boolean' },
                message: { type: 'string' },
                html: { type: 'string' },
              },
              required: ['success', 'message', 'html'],
            },
          },
        },
      },
      500: {
        description: 'Failed to render or send email',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                statusCode: { type: 'number', example: 500 },
                statusMessage: { type: 'string' },
              },
              required: ['statusCode', 'statusMessage'],
            },
          },
        },
      },
    },
  },
})

export default defineEventHandler(async (event) => {
  const body = await readBody<NuxtGenEmailsApiBody>(event)

  const templateData = body?.templateData ?? {}
  const sendData = body?.sendData ?? {}

  try {
    const { emailsDir } = useRuntimeConfig().nuxtGenEmails as { emailsDir: string }
    registerMjmlPartials(emailsDir)
    const mjmlSource = readFileSync(join(emailsDir, '${emailPath}.mjml'), 'utf-8')
    const compiledTemplate = Handlebars.compile(mjmlSource)
    const mjmlString = compiledTemplate(templateData)
    const { html, errors } = mjml2html(mjmlString)

    if (errors && errors.length > 0) {
      throw new Error('MJML compilation errors: ' + errors.map(e => e.formattedMessage).join('; '))
    }

    const nitro = useNitroApp()
    // @ts-ignore - custom hook
    await nitro.hooks.callHook('nuxt-generation-emails:send', { html, data: sendData })

    return { success: true, message: 'Email rendered successfully', html }
  }
  catch (error: unknown) {
    const message = error instanceof Error ? error.message : 'Failed to render or send email'
    throw createError({ statusCode: 500, statusMessage: message })
  }
})
`
}
