/* eslint-disable */
// This file is generated by nuxt-generation-emails. Do not modify it manually.
// To regenerate, run: npx nuxt-generation-emails regenerate

import { defineEventHandler, readBody, createError } from 'h3'
import { useNitroApp, getSendGenEmailsHandler } from '#imports'
import { render } from '@vue-email/render'
import EmailTemplate from '~/emails/v1/test.vue'
import type { TestData } from '~/emails/v1/test.data'

defineRouteMeta({
  openAPI: {
    tags: ['nuxt-generation-emails'],
    summary: 'Send test email',
    description: 'Render and send the v1/test email template.',
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            example: {
  "previewText": "Your order has been confirmed and is being prepared for shipment.",
  "customerFirstName": "Avery",
  "orderNumber": "NGE-904381",
  "orderDate": "February 13, 2026",
  "deliveryEstimate": "February 18, 2026",
  "storeName": "Northwind Outfitters",
  "supportEmail": "support@northwindoutfitters.com",
  "orderUrl": "https://example.com/orders/NGE-904381",
  "shippingMethod": "Standard (3-5 business days)",
  "paymentMethod": "Visa •••• 4242",
  "shippingCost": 8.99,
  "tax": 14.82,
  "items": [
    {
      "name": "Evergreen Insulated Bottle - 20oz",
      "quantity": 1,
      "unitPrice": 32
    },
    {
      "name": "Trail Running Socks (3-Pack)",
      "quantity": 2,
      "unitPrice": 12.5
    },
    {
      "name": "Summit Daypack - Slate",
      "quantity": 1,
      "unitPrice": 79
    }
  ],
  "shippingAddress": {
    "name": "Avery Johnson",
    "line1": "2241 Pine Street",
    "line2": "Apt 8C",
    "city": "Seattle",
    "state": "WA",
    "postalCode": "98101",
    "country": "United States"
  }
},
            additionalProperties: true,
            description: 'TestData payload',
          },
        },
      },
    },
    responses: {
      200: {
        description: 'Email rendered successfully',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                success: { type: 'boolean' },
                message: { type: 'string' },
                html: { type: 'string' },
              },
              required: ['success', 'message', 'html'],
            },
          },
        },
      },
      500: {
        description: 'Failed to render or send email',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                statusCode: { type: 'number', example: 500 },
                statusMessage: { type: 'string' },
              },
              required: ['statusCode', 'statusMessage'],
            },
          },
        },
      },
    },
  },
})

export default defineEventHandler(async (event) => {
  // Read the POST body as typed data. Type safety in JavaScript? What a time to be alive.
  const body = await readBody<TestData>(event)


  try {
      const html = await render(EmailTemplate, body, { pretty: true })

    const nitro = useNitroApp()
    const sendGenEmailsHandler = getSendGenEmailsHandler()

    // If sendGenEmails function is provided in config, use it
    if (sendGenEmailsHandler) {
      await sendGenEmailsHandler(html, body)
    }
    else {
      // Otherwise, call the Nitro hook to allow users to send the email
      // This is where users can hook in their Resend/SendGrid/carrier pigeon integration
      // @ts-ignore - custom hook not recognized by Nitro types at compile time
      await nitro.hooks.callHook('nuxt-gen-emails:send', {
        html,
        data: body,
      })
    }

    return {
      success: true,
      message: 'Email rendered successfully', // "Successfully" is doing a lot of work here
      html, // Return the HTML because why not, we already have it
    }
  }
  catch (error: unknown) {
    // Error handling: where we pretend we know what went wrong
    // Check instanceof Error because JavaScript lets you throw ANYTHING. Strings, numbers, objects, your dignity.
    const message = error instanceof Error ? error.message : 'Failed to render or send email'
    throw createError({
      statusCode: 500, // The universal "something broke" code
      statusMessage: message,
    })
  }
})
